name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag sreelekshman/upnas:latest
    - name: Push the image to DockerHub
      run: |
        docker login -u sreelekshman -p ${{ secrets.DOCKER_HUB }}
        docker push sreelekshman/upnas:latest
